# Task - 1:
## Create a Python program that converts between different units of measurement.

### The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

### Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.

### Conversion Options:
1. Length:

Convert meters (m) to feet (ft).
Convert feet (ft) to meters (m).

2. Weight:

Convert kilograms (kg) to pounds (lbs).
Convert pounds (lbs) to kilograms (kg).

3. Volume:

Convert liters (L) to gallons (gal).
Convert gallons (gal) to liters (L).

In [ ]:
def unit_converter():
    """Converts between units (length/weight/volume) with error handling."""
    try:
        category = input("Choose category (length/weight/volume): ").lower()
        if category not in ["length", "weight", "volume"]:
            raise ValueError("Invalid category")

        value = float(input("Enter value: "))
        direction = input("Choose conversion:\n1. m→ft\n2. ft→m\n3. kg→lbs\n4. lbs→kg\n5. L→gal\n6. gal→L\n> ")

        conversions = {
            "1": (value * 3.28084, f"{value}m = {value*3.28084:.2f}ft"),
            "2": (value / 3.28084, f"{value}ft = {value/3.28084:.2f}m"),
            "3": (value * 2.20462, f"{value}kg = {value*2.20462:.2f}lbs"),
            "4": (value / 2.20462, f"{value}lbs = {value/2.20462:.2f}kg"),
            "5": (value * 0.264172, f"{value}L = {value*0.264172:.2f}gal"),
            "6": (value / 0.264172, f"{value}gal = {value/0.264172:.2f}L")
        }

        return conversions[direction][1]

    except ValueError:
        return "Invalid input. Enter numbers only."
    except KeyError:
        return "Invalid conversion choice."

# Test
unit_converter()

Choose category (length/weight/volume): length
Enter value: 234
Choose conversion:
1. m→ft
2. ft→m
3. kg→lbs
4. lbs→kg
5. L→gal
6. gal→L
> 1


'234.0m = 767.72ft'

# Task - 2:
## Create a Python program that performs various mathematical operations on a list of numbers.

### The Program should:

1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

### Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def math_operations():
    """Performs sum/avg/max/min on a list of numbers."""
    def _sum(nums): return sum(nums)
    def _avg(nums): return sum(nums)/len(nums)
    def _max(nums): return max(nums)
    def _min(nums): return min(nums)

    try:
        op = input("Choose operation (sum/avg/max/min): ").lower()
        nums = list(map(float, input("Enter numbers (space-separated): ").split()))
        if not nums: raise ValueError("Empty list")

        return {
            "sum": _sum(nums),
            "avg": _avg(nums),
            "max": _max(nums),
            "min": _min(nums)
        }[op]

    except ValueError: return "Invalid input"
    except KeyError: return "Invalid operation"

math_operations()

Choose operation (sum/avg/max/min): avg
Enter numbers (space-separated): 12 34 22 56 67


38.2

# Exercise on List Manipulation:

## 1. Extract Every Other Element:

## Write a Python function that extracts every other element from a list, starting from the first element.

### Requirements:

Define a function extract every other(lst) that takes a list lst as input and returns a new list containing every other element from the original list.
Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

## 2. Slice a Sublist:

## Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

### Requirements:

Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).
Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

## 3. Reverse a List Using Slicing:

## Write a Python function that reverses a list using slicing.

### Requirements:

Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.
Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

## 4. Remove the First and Last Elements:

## Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

### Requirements:

Define a function remove first last(lst) that takes a list lst and returns a sublist without the first and last elements using slicing.
Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

## 5. Get the First n Elements:

## Write a Python function that extracts the first n elements from a list.

### Requirements:

Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.
Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

## 6. Extract Elements from the End:

## Write a Python function that extracts the last n elements of a list using slicing.

### Requirements:

Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.
Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

## 7. Extract Elements in Reverse Order:

## Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

### Requirements:

Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.
Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
# 1. Extract Every Other Element
def extract_every_other(lst):
    return lst[::2]
list0 = [1, 2, 3, 4, 5, 6]
print(extract_every_other(list0))


# 2. Get Sublist
def get_sublist(lst, start, end):
  return lst[start:end+1]
list0 = [1, 2, 3, 4, 5, 6]
print(get_sublist(list0, 2, 4))


# 3. Reverse List
def reverse_list(lst):
  return lst[3]
list1 = [1, 2, 3, 4, 5]
print("quotient", reverse_list(list1))

# 4. Remove First/Last
def remove_first_last(lst):
  return lst[1:-1] if len(lst) > 2 else []
print(remove_first_last(list1))

# 5. First N Elements
def get_first_n(lst, n):
  return lst[:n]
print(get_first_n(list1, 3))

# 6. Last N Elements
def get_last_n(lst, n):
  return lst[-n:]
print(get_last_n(list1, 2))

# 7. Reverse Skip
def reverse_skip(lst):
  return lst[-2::-2]
print(reverse_skip(list))


[1, 3, 5]
[3, 4, 5]
quotient 4
[2, 3, 4]
[1, 2, 3]
[4, 5]
list[slice(-2, None, -2)]


# 4.3. Exercise on Nested List:

## 1. Flatten a Nested List:
## Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

### Requirements:
Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.
Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

## 2. Accessing Nested List Elements:
## Write a Python function that extracts a specific element from a nested list given its indices.

### Requirements:
Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.
Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,2], the output should be 6.

## 3. Sum of All Elements in a Nested List:
## Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

### Requirements:
Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.
Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

## 4. Remove Specific Element from a Nested List:
## Write a Python function that removes all occurrences of a specific element from a nested list.

### Requirements:
Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.
Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].

## 5. Find the Maximum Element in a Nested List:
## Write a Python function that finds the maximum element in a nested list (regardless of depth).

### • Requirements:
Define a function find max(lst) that takes a nested list lst and returns the maximum element.
Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

## 6. Count Occurrences of an Element in a Nested List:
## Write a Python function that counts how many times a specific element appears in a nested list.

### Requirements:
Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.
Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.

## 7. Flatten a List of Lists of Lists:
## Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

### Requirements:
Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.
Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

## 8. Nested List Average:
## Write a Python function that calculates the average of all elements in a nested list.

### Requirements:
Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.
Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
# 1. Flatten Nested List
def flatten(lst):
    return [item for sublist in lst for item in sublist]
nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)
print(result)


# 2. Access Nested Element
def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst


nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)
print(result)


# 3. Sum Nested List
def sum_nested(lst):
    total = 0
    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)
        else:
            total += element
    return total


nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)
# 4. Remove Element
def remove_element(lst, elem):
    return [remove_element(i, elem) if isinstance(i, list) else i for i in lst if i != elem]

listD = [[1, 2], [3, 2], [4, 5]]
print(remove_element(listD, 2))

[1, 2, 3, 4, 5]
6
21
[[1], [3], [4, 5]]


In [ ]:
# 5. Find Max
def find_max(lst):
    max_value = float('-inf')  # Initialize max_value to negative infinity

    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))  # Recursively find max in sublists
        else:
            max_value = max(max_value, item)  # Compare with current max

    return max_value


nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print(result)


6


In [ ]:
# 6. Count Occurrences
def count_occurrences(lst, elem):
    count = 0  # Initialize count

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count in sublists
        elif item == elem:
            count += 1  # Increment count if the element matches

    return count


nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)
print(result)


3


In [ ]:
# 7. Deep Flatten
def deep_flatten(lst):
    flattened = []  # Initialize an empty list to store the flattened elements

    for item in lst:
        if isinstance(item, list):
            flattened.extend(deep_flatten(item))  # Recursively flatten sublists
        else:
            flattened.append(item)  # Add non-list items directly to the flattened list

    return flattened
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# 8. Nested Average
def average_nested(lst):
    def deep_flatten(lst):
        flattened = []
        for item in lst:
            if isinstance(item, list):
                flattened.extend(deep_flatten(item))  # Recursively flatten sublists
            else:
                flattened.append(item)
        return flattened

    flattened_list = deep_flatten(lst)  # Get a single-level list
    if not flattened_list:  # Handle empty lists
        return 0

    return sum(flattened_list) / len(flattened_list)  # Calculate the average


nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print(result)

3.5


# Basic Vector and Matrix Operation with Numpy.
## Problem - 1: Array Creation:
### Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

empty_array = np.empty((2, 2))
print("Empty 2x2 Array:\n", empty_array)

ones_array = np.ones((4, 2))
print("\nAll Ones 4x2 Array:\n", ones_array)

fill_value_array = np.full((3, 3), 7)
print("\n3x3 Array Filled with 7:\n", fill_value_array)

reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Array with Same Shape as Reference Array:\n", zeros_like_array)

ones_like_array = np.ones_like(reference_array)
print("\nOnes Array with Same Shape as Reference Array:\n", ones_like_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)

Empty 2x2 Array:
 [[2.09602622e-316 0.00000000e+000]
 [1.67709717e+243 1.10441143e+155]]

All Ones 4x2 Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3x3 Array Filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array with Same Shape as Reference Array:
 [[0 0 0]
 [0 0 0]]

Ones Array with Same Shape as Reference Array:
 [[1 1 1]
 [1 1 1]]

Converted NumPy Array:
 [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing: Complete the following tasks:

Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}
Create a 3X3 identity matrix.{Hint:np.eye()}
Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}
Create a 10X10 array with random values and find the minimum and maximum values.
Create a zero array of size 10 and replace 5th element with 1.
Reverse an array arr = [1,2,0,0,4,0].
Create a 2d array with 1 on border and 0 inside.
Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_10_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array_30 = np.random.random(30)
mean_value = random_array_30.mean()
print("\nRandom array of size 30:\n", random_array_30)
print("Mean of the array:", mean_value)

# 5. Create a 10x10 array with random values and find the min and max values
random_matrix_10x10 = np.random.random((10, 10))
min_value = random_matrix_10x10.min()
max_value = random_matrix_10x10.max()
print("\n10x10 Random Matrix:\n", random_matrix_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 is the 5th element (0-based indexing)
print("\nZero Array with 5th Element as 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with Border 1 and Inside 0:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill 1 in alternate positions
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
 [0.62220859 0.08179515 0.01931555 0.66726006 0.95707194 0.96007019
 0.73215978 0.11397544 0.489317   0.93676993 0.32960806 0.94959839
 0.69548324 0.29320812 0.15981453 0.57280576 0.2097003  0.42983601
 0.30228361 0.32952911 0.37258744 0.49792156 0.30383242 0.38280643
 0.98417799 0.78048788 0.88318533 0.92469137 0.82689251 0.78372322]
Mean of the array: 0.5530705642938905

10x10 Random Matrix:
 [[8.16285009e-01 9.69001811e-01 4.13147787e-01 5.41988102e-01
  2.50160567e-01 1.61965662e-01 5.43706301e-01 4.11458522e-01
  1.64115519e-01 7.72552015e-01]
 [9.99418603e-01 2.40252340e-01 5.82676833e-01 6.42860221e-01
  1.62874994e-01 5.58898580e-01 8.04699098e-01 8.42383817e-01
  4.60374676e-01 6.20006

## Problem - 3: Array Operations:
### For the following arrays:
### x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
### v = np.array([9,10]) and w = np.array([11,12]);
### Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Define the given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays (element-wise)
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays (element-wise)
subtract_xy = x - y
print("\nSubtraction of x and y:\n", subtract_xy)

# 3. Multiply the array x with an integer (e.g., 3)
multiply_x = x * 3
print("\nMultiplication of x with 3:\n", multiply_x)

# 4. Find the square of each element of x
square_x = np.square(x)
print("\nSquare of each element in x:\n", square_x)

# 5. Find the dot product
dot_vw = np.dot(v, w)  # Dot product of vectors v and w
dot_xv = np.dot(x, v)  # Dot product of matrix x and vector v
dot_xy = np.dot(x, y)  # Dot product of matrices x and y

print("\nDot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

# 6. Concatenate x and y along rows (axis=0)
concat_xy = np.concatenate((x, y), axis=0)
print("\nConcatenation of x and y along rows:\n", concat_xy)

# Concatenate v and w along columns (reshaping them to column vectors)
concat_vw = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("\nConcatenation of v and w along columns:\n", concat_vw)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)  # Attempting to concatenate x and v
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError while concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


## Problem - 4: Matrix Operations:


# Experiment: How Fast is Numpy?
## In this exercise, you will compare the performance and implementation of operations using plain Python
## lists (arrays) and NumPy arrays. Follow the instructions:
### 1. Element-wise Addition:
Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
import time
import numpy as np

# Create two lists of size 1,000,000 with random values
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000000, 0, -1)]

# Measure time for Python List element-wise addition
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()
print(f"Time taken for element-wise addition using Python Lists: {end_time - start_time} seconds")

# Create two numpy arrays of size 1,000,000 with random values
array1 = np.arange(1, 1000001)
array2 = np.arange(1000000, 0, -1)

# Measure time for Numpy Array element-wise addition
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
print(f"Time taken for element-wise addition using Numpy Arrays: {end_time - start_time} seconds")


Time taken for element-wise addition using Python Lists: 0.07983636856079102 seconds
Time taken for element-wise addition using Numpy Arrays: 0.003934621810913086 seconds


### 2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
import time
import numpy as np

# Create two lists of size 1,000,000 with random values
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000000, 0, -1)]

# Measure time for Python List element-wise multiplication
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()
print(f"Time taken for element-wise multiplication using Python Lists: {end_time - start_time} seconds")

# Create two numpy arrays of size 1,000,000 with random values
array1 = np.arange(1, 1000001)
array2 = np.arange(1000000, 0, -1)

# Measure time for Numpy Array element-wise multiplication
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
print(f"Time taken for element-wise multiplication using Numpy Arrays: {end_time - start_time} seconds")


Time taken for element-wise multiplication using Python Lists: 0.10437607765197754 seconds
Time taken for element-wise multiplication using Numpy Arrays: 0.0053250789642333984 seconds


### 3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time
import numpy as np

# Create two lists of size 1,000,000 with random values
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000000, 0, -1)]

# Measure time for Python List dot product
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()
print(f"Time taken for dot product using Python Lists: {end_time - start_time} seconds")

# Create two numpy arrays of size 1,000,000 with random values
array1 = np.arange(1, 1000001)
array2 = np.arange(1000000, 0, -1)

# Measure time for Numpy Array dot product
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print(f"Time taken for dot product using Numpy Arrays: {end_time - start_time} seconds")


Time taken for dot product using Python Lists: 0.1007850170135498 seconds
Time taken for dot product using Numpy Arrays: 0.0012829303741455078 seconds


### 4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import time
import numpy as np

# Define matrix size
N = 1000  # Matrix size 1000x1000

# Create two random 1000x1000 matrices using Python lists
matrix1_list = [[np.random.rand() for _ in range(N)] for _ in range(N)]
matrix2_list = [[np.random.rand() for _ in range(N)] for _ in range(N)]

# Measure time for matrix multiplication using Python Lists
start_time = time.time()
result_list = [[sum(matrix1_list[i][k] * matrix2_list[k][j] for k in range(N)) for j in range(N)] for i in range(N)]
end_time = time.time()
print(f"Time taken for matrix multiplication using Python Lists: {end_time - start_time:.5f} seconds")

# Create two random 1000x1000 matrices using NumPy arrays
matrix1_array = np.random.rand(N, N)
matrix2_array = np.random.rand(N, N)

# Measure time for matrix multiplication using NumPy Arrays
start_time = time.time()
result_array = np.dot(matrix1_array, matrix2_array)
end_time = time.time()
print(f"Time taken for matrix multiplication using NumPy Arrays: {end_time - start_time:.5f} seconds")


Time taken for matrix multiplication using Python Lists: 175.36505 seconds
Time taken for matrix multiplication using NumPy Arrays: 0.06694 seconds
